### ISSUE TITLE
Starting version number

### ISSUE THREAD

**Issue by marclaporte** [tkz1937/ntp#1]
$app['version'] = '2.5.0';
https://github.com/tkz1937/ntp/blob/master/ntp/deploy/info.php

2.4:
https://github.com/tkz1937/ntp/blob/master/ntp/packaging/app-ntp.spec

I find odd that first version of the app is more than 1.0

It's should reach 1.0 once it basically works

**Comment by tkz1937** [comment]
I corrected that
